site_name: phanisana - PHP library to convert number, date and time into Malagasy language
site_url: !ENV READTHEDOCS_CANONICAL_URL
theme:
  name: material
  custom_dir: docs/overrides
extra_javascript:
  - javascripts/readthedocs.js
nav:
  - 'Introduction': 'index.md'
  - 'Installation': 'installation.md'
  - 'Usages':
    - 'Number Converter': 'usages/number.md'